# Generated by Django 6.0.1 on 2026-02-03 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('FRESHER', 'Fresher'), ('1-3', '1–3 Years'), ('3-5', '3–5 Years'), ('5+', '5+ Years')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.IntegerField(db_index=True, help_text='Monthly salary'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_title'], name='VCS_job_job_tit_81ed20_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='VCS_job_locatio_67e9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience'], name='VCS_job_experie_f8f0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_range'], name='VCS_job_salary__0130df_idx'),
        ),
    ]
